spring:
  application:
    name: euraka-server01

server:
  port: 8060

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0