server:
  port: 8001

spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
#      routes:
#        - id: authService
#          uri: http://localhost:8040/auth/login
#          predicates:
#            - Path=/AUTHEN/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/,http://localhost:8061/eureka/