spring:
  application:
    name: euraka-server

server:
  port: 8060

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false